---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom CloudFormation KMS Provider
Resources:
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    DependsOn: LambdaPolicy
    Properties:
      Description: CloudFormation Custom:KMSGrant provider
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-kms-provider:1.0.1
      FunctionName: binxio-cfn-kms-provider
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt 'LambdaRole.Arn'

  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNKMSProvider
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'kms:CreateGrant'
              - 'kms:RetireGrant'
              - 'kms:RevokeGrant'
              - 'kms:ListAliases'
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNCustomProviderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${CFNCustomProvider}'
      RetentionInDays: 7

